# Generated by Django 4.0.1 on 2022-01-19 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='togri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_soz', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='notogri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_soz', models.CharField(max_length=20)),
                ('togrisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.togri')),
            ],
        ),
    ]
